### ISSUE TITLE
Request for Permission to Rewrite Novaflow-WAF from Rust to Go

### ISSUE THREAD

**Issue by revolusiber** [DwiyanTech/novaflow#1]
Hi, I have sent you an email at ahmad.dwiyan14@gmail.com regarding the this request. Can you please check the email?

Thanks.

Regards.

**Comment by DwiyanTech** [comment]
i already answer your questions, i want keep this projects on track on rust, at the first place i want use in go (i use on my day-to-day using go cause fast development and simple code), but after several research it will not suite for minimum resource especially memory (since gorountines and garbage collector use memory), the details are on email thanks
